# Generated by Django 4.1.7 on 2024-09-06 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('SOBRECONSUMO', 'Sobreconsumo'), ('BAJO_CONSUMO', 'Bajo_consumo'), ('PICO_CORRIENTE', 'Pico_corriente'), ('APAGON', 'Apagon')], max_length=15)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.device')),
            ],
        ),
    ]
