# Generated by Django 4.1.7 on 2024-09-06 15:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispositivos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('reading_id', models.AutoField(primary_key=True, serialize=False)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current', models.DecimalField(decimal_places=2, max_digits=10)),
                ('energy', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('device_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispositivos.device')),
            ],
        ),
    ]
