# Generated by Django 4.1.7 on 2024-07-06 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='photo',
        ),
    ]
